services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mixsum_db
      MYSQL_USER: mixsum_user
      MYSQL_PASSWORD: mixsum_pass
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - internal

  mixsum_admin:
    build: ./admin.mixsum.co.id
    container_name: mixsum_admin_app
    restart: unless-stopped
    ports:
      - "8004:80"
    volumes:
      - /var/www/html/admin.mixsum.co.id/public:/var/www/html/public
      - /var/www/html/admin.mixsum.co.id/storage/app/public:/var/www/html/storage/app/public
    depends_on:
      - mysql
    environment:
      APP_DEBUG: true
      APP_URL: https://admin.mixsum.co.id
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: mixsum_db
      DB_USERNAME: mixsum_user
      DB_PASSWORD: mixsum_pass
    networks:
      - internal

  satu:
    build: ./satu
    container_name: satu_app
    ports:
      - "8001:80"
    networks:
      - internal

  dua:
    build: ./dua
    container_name: dua_app
    ports:
      - "8002:80"
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  mysql_data:
